/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppNftRouteImport } from './routes/app.nft'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppKycRouteImport } from './routes/app.kyc'
import { Route as AppInvestRouteImport } from './routes/app.invest'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppDepositRouteImport } from './routes/app.deposit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppNftRoute = AppNftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestRoute = AppInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/invest': typeof AppInvestRoute
  '/app/kyc': typeof AppKycRoute
  '/app/market': typeof AppMarketRoute
  '/app/nft': typeof AppNftRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/invest': typeof AppInvestRoute
  '/app/kyc': typeof AppKycRoute
  '/app/market': typeof AppMarketRoute
  '/app/nft': typeof AppNftRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/home': typeof AppHomeRoute
  '/app/invest': typeof AppInvestRoute
  '/app/kyc': typeof AppKycRoute
  '/app/market': typeof AppMarketRoute
  '/app/nft': typeof AppNftRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/deposit'
    | '/app/home'
    | '/app/invest'
    | '/app/kyc'
    | '/app/market'
    | '/app/nft'
    | '/app/referral'
    | '/app/transactions'
    | '/app/wallet'
    | '/app/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/deposit'
    | '/app/home'
    | '/app/invest'
    | '/app/kyc'
    | '/app/market'
    | '/app/nft'
    | '/app/referral'
    | '/app/transactions'
    | '/app/wallet'
    | '/app/withdraw'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/deposit'
    | '/app/home'
    | '/app/invest'
    | '/app/kyc'
    | '/app/market'
    | '/app/nft'
    | '/app/referral'
    | '/app/transactions'
    | '/app/wallet'
    | '/app/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nft': {
      id: '/app/nft'
      path: '/nft'
      fullPath: '/app/nft'
      preLoaderRoute: typeof AppNftRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kyc': {
      id: '/app/kyc'
      path: '/kyc'
      fullPath: '/app/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invest': {
      id: '/app/invest'
      path: '/invest'
      fullPath: '/app/invest'
      preLoaderRoute: typeof AppInvestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDepositRoute: typeof AppDepositRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInvestRoute: typeof AppInvestRoute
  AppKycRoute: typeof AppKycRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNftRoute: typeof AppNftRoute
  AppReferralRoute: typeof AppReferralRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepositRoute: AppDepositRoute,
  AppHomeRoute: AppHomeRoute,
  AppInvestRoute: AppInvestRoute,
  AppKycRoute: AppKycRoute,
  AppMarketRoute: AppMarketRoute,
  AppNftRoute: AppNftRoute,
  AppReferralRoute: AppReferralRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletRoute: AppWalletRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
